### ISSUE TITLE
cannot complile

### ISSUE THREAD

**Issue by georgbuechner** [kava-i/Der-Zug#2]
Installed Ciavelli Package manager successfully
-- Boost version: 1.65.1
CMake Error at CMakeLists.txt:37 (add_git_cmake_project):
  Unknown CMake command "add_git_cmake_project".

-- Configuring incomplete, errors occurred!

**Comment by georgbuechner** [comment]
- Boost version: 1.65.1

**Comment by alleonhardt** [comment]
Should be fixed by now
