### ISSUE TITLE
Allow Text-Elements to throw events

### ISSUE THREAD

**Issue by ambientgoth** [kava-i/Der-Zug#68]

**Comment by georgbuechner** [comment]
This functionlity is generally implemented. The events are added to `CPlayer::m_sStagedEvents`. The appendPrint function from CPlayer is no always checking for staged events and throwing these when exits. 

There are to kinds of events pEvents (permable events) and otEvents (one time events) the later are always delete after they have been called. 

This should be also implemented for the dialog and the fighting class in a similar manner, to prevent events being thrown all over the place. As there are some events, that want to been thrown _before_ appending print, maybe two separate "staged events" could be interesting: `staged_prev_events` and `staged_after_events` but we will see about that.

**Comment by georgbuechner** [comment]
Decided to only use this functionality, when throwing events from yaml files. 
Events thrown in c++ code are always executed directly. 
But it would be good to throw events directly from where they come (this means f.e., from dialog and from fight) 
Also all events when throw print in the console, from where they come.

**Comment by georgbuechner** [comment]
Events will still be thrown from EnhancedContext, not from fight/ dialog
